# Generated by Django 4.0.1 on 2023-10-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
